version: '3.8'

services:
  # Service MySQL
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - mysql_data:/var/lib/dummy-app

  # Service Redis
  redis:
    image: redis:latest
    hostname: redis

  # Service de l'application web
  app:
    hostname: mydocker
    build: .
    ports:
      - "1337:1337"
    expose:
      - 1337
    restart: on-failure
    environment:
      PORT: 1337
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      FILE_PATH_TO_CHECK: /app/index.ts
    volumes:
      - .:/app
    command: npm run develop

volumes:
  mysql_data:
